# Generated by Django 2.2.6 on 2022-05-18 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220518_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'Пост должен состоять минимум из двух символов')], verbose_name='Текст поста'),
        ),
    ]
