# Generated by Django 2.2.16 on 2022-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220602_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете добавить изображение к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
